name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Render Documentation
        uses: openactive/extension-documentation-generator@master
        with:
          header: header.md
          context: beta.jsonld
          with_issues: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true
          enable_jekyll: true

  dispatch:
    needs: deploy
    strategy:
      matrix:
        repo: ['OpenActive.NET', 'models-php', 'models-ruby', 'models-ts', 'developer-documentation']
    runs-on: ubuntu-latest
    steps:
      - name: Trigger tooling update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          repository: openactive/${{ matrix.repo }}
          event-type: data-models-update
